language: java
jdk:
  - oraclejdk8

sudo: required

services:
  - mysql

addons:
  firefox: latest
  chrome: stable
  hosts:
    - db.dev.local
    - api.dev.local
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

after_failure:
  - cat /home/travis/build/alobaton/spring-boot-seed/spring-boot-debug.log

branches:
  only: master

notifications:
  email: false

before_install:
  - mysql -e 'CREATE DATABASE `dev-db`;'
  - mysql -e "CREATE USER `dev-user`@`localhost` IDENTIFIED BY 'dev-password';"
  - mysql -e 'GRANT ALL PRIVILEGES ON * . * TO `dev-user`@`localhost`;'
  - mysql -e 'FLUSH PRIVILEGES;'

script:
  - cd apps && mvn clean install -Dspring.profiles.active=dev