version: "2.2"

services:
  api:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile_prod
    container_name: spring-boot-seed-prod
    image: spring-boot-seed/prod
    volumes:
      - ./api:/home/spring-boot-seed/api
    networks:
      - prod-network
    ports:
      - 8080:8080
      - 10001:10001
    mem_limit: 768m
    cpu_percent: 60

networks:
  prod-network: {}
